# Theme
remote_theme: epidrome/cover-card@v0.3

# Site Settings
title: 'epidrome'
description: 'surfer & scholar.'

# Online profiles
github-user: 'epidrome'
# telegram: 'epidrome'
scholar: 'http://scholar.epidro.me'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'
