# Theme
remote_theme: epidrome/cover-card

# Site Settings
name: 'epidrome'
description: 'surfer & scholar.'


github: 'epidrome'
keybase: 'epidrome'
telegram: 'epidrome'

avatar: 'assets/images/avatar.jpg'
background: 'assets/images/background.jpg'
favicon: 'assets/images/favicon.ico'


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-remote-theme
