# Theme
remote_theme: epidrome/cover-card

# Site Settings
title: 'epidrome'
description: 'surfer & scholar.'

# Online profiles
github: 'epidrome'
keybase: 'epidrome'
telegram: 'epidrome'
scholar: 'https://scholar.epidro.me'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

# Build settings
plugins:
  - jekyll-remote-theme
