# Theme
remote_theme: epidrome/cover-card

# Site Settings
title: 'epidrome'
description: 'surfer & scholar.'


github: 'epidrome'
keybase: 'epidrome'
telegram: 'epidrome'

avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-remote-theme
